version: '3.8'

services:
  mongo:
    image: 'mongo:latest'
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: senha123

networks: 
  postgres-compose-network:
    driver: bridge